import React, { Component } from 'react';
import styles from '../../styles/Home.module.css';
import { Button } from 'reactstrap';
import { Container, Row, Col } from 'reactstrap';
import IMAGES from '../../images';
import Flexbox from 'flexbox-react';
import Charity from './Charity'

const CHARITIES = [
  {name: "Cool Earth", image: IMAGES.james, ratePerKg: 0.00134, reference: ""},
  {name: "Vegan Outreach", image: IMAGES.abe, ratePerKg: 0.00691, reference: ""},
  {name: "Solar Aid", image: IMAGES.isabelle, ratePerKg: 0.0100, reference: ""},
]


class OffsetModal extends React.Component {
  render() {
    return (
      <div>
        <h2 className={styles.center}>Offset your Carbon Emissions</h2>
        <p className={styles.centerNoFlex}>
          Compensate for the emissions you've already generated by donating to a charity that
          actively eliminates CO2 emissions from the atmosphere.
        </p>
        <Flexbox className={styles.center}>
          {
            CHARITIES.map((charInfo) => {
              return <Charity info={charInfo} />;
            })
          }
        </Flexbox>
      </div>
    );
  }
}

export default OffsetModal;
