import React, { Component } from 'react';
import styles from '../../styles/Home.module.css';
import IMAGES from '../../images';
import Flexbox from 'flexbox-react';
import CharityCard from './CharityCard';
import { Button } from 'reactstrap';

class OffsetShowcase extends Component {
  constructor(props) {
    super(props);
    this.state = {
      charityList: []
    };

    //get information about charities to display
    window
      .fetch('/charities')
      .then(response => response.json())
      .then(data => this.setState({ charityList: data.charities }));
  }

  render() {
    return (
      <div>
        <p className={styles.centerNoFlex}>
          <p>
            Compensate for the emissions you've generated by donating to a charity that actively
            eliminates CO2 emissions from the atmosphere.
          </p>
          <Button outline color="primary">
            How does offsetting work?
          </Button>
        </p>
        <hr />
        <Flexbox className={styles.center}>
          {this.state.charityList.map(charInfo => {
            let isEnfin = charInfo.name === 'Enfin';
            let charImage = IMAGES[charInfo.name];
            return (
              <CharityCard
                name={charInfo.name}
                blurb={charInfo.blurb}
                ratePerKg={charInfo.ratePerKg}
                donateLink={charInfo.donateLink}
                infoLink={charInfo.infoLink}
                disabled={isEnfin}
                extraImagePadding={isEnfin}
                image={charImage}
              />
            );
          })}
        </Flexbox>
      </div>
    );
  }
}

export default OffsetShowcase;
